name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Check Docker Installation
      run: docker version

    - name: Build the Docker image
      run: docker build -t Hasanjawich/cicd-pipeline .
    - name: Push to Dockerhub
      run: docker push Hasanjawich/cicd-pipeline:latest